### ISSUE TITLE
[general] allow array in envvar

### ISSUE THREAD

**Issue by NicolasGeraud** [git-up/GitUp#444]
In `gravitee.yml` config file we can define list: 
```
management:
  mongodb:
    servers:
      - host: my.domain.com
      - port: 27017
```
But If we want to configure gravitee with system environment variables, we cannot use something like `GRAVITEE_MANAGEMENT_MONGODB_SERVERS[0]_HOST=my.domain.com` because `[`and `]` are forbidden.

We need to be able to express list like that : `GRAVITEE_MANAGEMENT_MONGODB_SERVERS_0_HOST`
